baseURL = "https://AxtengZwm.github.com"
languageCode = "zh-cn"
title = "学习笔记"
theme = "yinyang"
DefaultContentLanguage = "cn"

[author]
  name = "Axteng"
  homepage = "https://github.com/AxtengZwm/"

[languages]
  # [languages.en]
  #   contentDir = "content/en"
  #   languageName = "English"
  #   weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 1
    
pygmentsUseClasses = true
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "github"
    tabWidth = 4

[params]
# disqus = "sudri" # disqus account name
extraHead = ''
mainSections = ["posts"]
# googleAnalytics = ""
# description = ""

# [[params.socials]]
# name = "Github"
# link = "https://github.com/AxtengZwm/"

# [[params.socials]]
# name = "RSS"
# link = "/index.xml"

# [[params.socials]]
# name = "Mail"
# link = "mailto:AxtengZwm@google.com"

[[params.socials]]
name = "~"
link = "https://music.163.com/song?id=356827"